### PR TITLE
OneCodex -> One Codex (I know, I know...)

### PR DESCRIPTION
**Pull request by boydgreenfield**
Yes, this is a _tiny_ bit neurotic, but I've just been (internally) fighting for this space, and so hope a quick PR is OK... Promise I haven't broken any tests!

### CODE REVIEW

**Comment by boydgreenfield** [comment]
Oh – and I don't believe one can PR the repo "tagline", but I'd appreciate a quick edit there should you choose to accept this PR. :)

**Comment by LuRsT** [comment]
Sure thing @boydgreenfield, thanks for your contribution!

**Comment by LuRsT** [comment]
Unfortunately, I cannot change the tagline, let's hope @Phelimb remembers :)

**Comment by boydgreenfield** [comment]
Haha, thanks @LuRsT – and I'll try to make a more meaningful contribution next time! ;)

**Pull request merged**
